name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Grunt
      run: npm install grunt --save-dev

    - name: Use Node.js ${{ matrix.node-version }}
      uses: node20
      main: 'main.js'

    - name: Build
      run: |
        npm install
        grunt
